[build-system]
requires = [
    'setuptools>=59',
    'wheel',
    'cffi==1.15.1',
    'cryptography==41.0.1',
    'pycparser==2.21',
    'pycryptodome==3.18.0',
    'requests==2.31',
]
build-backend = 'setuptools.build_meta'